/**
 * YjsManager — CRDT-based shared state synchronization over WebRTC DataChannel.
 *
 * ## How Yjs CRDT Works
 *
 * CRDT (Conflict-free Replicated Data Type) — это математическая модель для синхронизации
 * распределённого состояния без центрального сервера. В отличие от Operational
 * Transformation (OT), CRDT не требует порядка применения операций: каждое изменение
 * может быть применено в любом порядке на любом узле, и все узлы всегда придут
 * к одинаковому состоянию.
 *
 * Yjs использует Block CRDT для текстовых структур и Map CRDT для ключ-значение хранилищ.
 * Ключевые преимущества:
 * - Операционная сложность: O(log n) для большинства операций
 * - Нет необходимости в центральном координационном сервере
 * - Одновременные редактирования от разных пиров автоматически разрешаются
 * - Обновления компактные (только разница, не полное состояние)
 *
 * ## Why Y.Map and Y.Text
 *
 * - Y.Map — это CRDT-реализация ассоциативного массива (key-value store). Идеально
 *   для хранения объектов на столе (table objects): ключ = objectId, значение =
 *   {x, y, rotation, scale, type, fileId}. Y.Map обеспечивает, что одновременные
 *   вставки/обновления/удаления ключей будут согласованы на всех пирах.
 *
 * - Y.Text — это CRDT-реализация последовательности символов. В отличие от обычного
 *   string, Y.Text хранит каждый символ как отдельный элемент с уникальным ID, что
 *   позволяет нескольким пользователям редактировать текст одновременно без конфликтов.
 *   Используется для shared text notes.
 *
 * ## How Yjs Updates Are Serialized and Sent Over DataChannel
 *
 * Yjs генерирует обновления в бинарном формате (Y Uint8Array encoding). Для передачи
 * через WebRTC DataChannel (который принимает string, ArrayBuffer или Blob) мы:
 *
 * 1. Подписываемся на событие `update` на Y.Doc через callback `((update: Uint8Array, origin: any) => ...)`
 * 2. Конвертируем Uint8Array в base64 строку через `btoa(String.fromCharCode(...bytes))`
 * 3. Отправляем через DataChannel как JSON: `{ __yjs__: true, update: "base64...", peerId: "..." }`
 * 4. Получающий пир парсит JSON, извлекает base64, конвертирует обратно в Uint8Array
 * 5. Применяет обновление через `Y.applyUpdate(doc, updateBytes, sourcePeerId)`
 *
 * Параметр `origin` в update callback используется для loop avoidance: мы не отправляем
 * обновления, созданные текущим пиrom (origin !== null означает обновление от другого пира).
 * Однако, мы всё равно передаём их дальше в mesh для полной репликации.
 */

import * as Y from "yjs";

/**
 * Типизированное сообщение для Yjs updates через DataChannel.
 * Сообщения, начинающиеся с __yjs__, считаются Yjs update сообщениями.
 */
interface YjsUpdateMessage {
  __yjs__: true;
  update: string; // base64-encoded Yjs binary update
  peerId: string; // ID пира, который создал это обновление
}

/** Сообщение для room events (peer join/leave for CRDT sync) */
interface YjsRoomMessage {
  __yjs__: false;
  type: "peer-joined" | "peer-left" | "sync-request" | "sync-response";
  peerId: string;
  update?: string; // base64-encoded full doc state (for sync-response)
}

/** Структура данных объекта на столе */
export interface TableObjectData {
  x: number;
  y: number;
  rotation: number;
  scale: number;
  type: "token" | "terrain" | "bg" | "note" | "custom";
  fileId?: string; // reference to synced asset
  name?: string;
  id?: string; // optional explicit ID (if not generated by Y.Map)
}

/** Initial state для новых объектов */
interface DefaultTableObjectData {
  x: number;
  y: number;
  rotation: number;
  scale: number;
  type: "custom";
  fileId?: string;
  name?: string;
}

type YjsCallback = (update: YjsUpdateMessage) => void;
type RoomCallback = (event: "peer-joined" | "peer-left", peerId: string) => void;
type ChangeEventType =
  | "add"
  | "update"
  | "delete"
  | "batch-start"
  | "batch-end"
  | "clear";

type ObjectsChangeCallback = (
  eventType: ChangeEventType,
  details: Record<string, unknown>
) => void;

/**
 * YjsManager управляет синхронизацией CRDT состояния через WebRTC DataChannel.
 *
 * Использует Yjs Doc с Y.Map для объектов стола и Y.Text для заметок.
 * Обновления сериализуются в base64 и отправляются напрямую между пирами
 * через DataChannel.
 *
 * Для Phase 1 (mesh с до 3 соединений: GM-Player, GM-Player) каждое обновление
 * отправляется всем подключённым пирам через их DataChannel.
 */
export class YjsManager {
  /** Yjs Doc — ядро CRDT синхронизации */
  private doc: Y.Doc;

  /**
   * Y.Map "objects" — хранит table objects.
   * Key: objectId (string, typically UUID)
   * Value: Y.Map с полями {x, y, rotation, scale, type, fileId, name}
   *
   * Используем Y.Map вместо Y.Array потому что:
   * 1. У нас есть уникальные ID для каждого объекта
   * 2. O(1) lookup по ключу
   * 3. Легко добавлять/обновлять/удалять объекты
   */
  private objectsMap: Y.Map<Y.Map<unknown>>;

  /** Y.Text "notes" — для shared text notes */
  private notesText: Y.Text;

  /** DataChannel, используемый для передачи Yjs updates */
  private dataChannel: RTCDataChannel | null = null;

  /** Собственный peer ID для идентификации в сети */
  private readonly localPeerId: string;

  /** Флаг инициализации */
  private initialized = false;

  /** Коллекция колбэков для входящих Yjs updates */
  private updateListeners = new Set<YjsCallback>();

  /** Коллекция колбэков для room events */
  private roomListeners = new Set<RoomCallback>();

  /** Коллекция колбэков для изменений objectsMap */
  private objectsChangeListeners = new Set<ObjectsChangeCallback>();

  /** Коллекция колбэков для изменений notesText */
  private notesChangeListeners = new Set<ObjectsChangeCallback>();

  /**
   * @param peerId Уникальный идентификатор этого пира (например, "A", "B")
   */
  constructor(peerId: string) {
    this.localPeerId = peerId;

    // Создаём Yjs Doc с режимом persistence: false (state восстанавливается из P2P)
    this.doc = new Y.Doc();

    // Получаем Y.Map "objects" или создаём новый
    this.objectsMap = this.doc.getMap<Y.Map<unknown>>("objects");

    // Получаем Y.Text "notes" или создаём новый
    this.notesText = this.doc.getText("notes");

    // Наблюдение за глубокими изменениями в objectsMap
    this.objectsMap.observeDeep(this.handleObjectsDeepChange.bind(this));

    // Наблюдение за изменениями в notesText
    this.notesText.observe(this.handleNotesChange.bind(this));

    // Слушаем update events от Yjs (binary updates from local changes)
    this.doc.on("update", this.handleYjsUpdate.bind(this));
  }

  /**
   * Инициализация Yjs Doc и shared структур.
   *
   * В Phase 1 структуры фиксированы: objects (Y.Map) и notes (Y.Text).
   * В будущих фазах можно добавить:
   * - Y.Array "tokens" для токенов с отслеживанием позиции
   * - Y.Map "grid" для настроек сетки
   * - Y.Map "camera" для синхронизации камеры
   */
  init(): void {
    if (this.initialized) {
      console.warn("[YjsManager] Already initialized, ignoring duplicate init()");
      return;
    }
    console.log(`[YjsManager] Initialized with peerId: ${this.localPeerId}`);
    this.initialized = true;
  }

  /**
   * Подключение к DataChannel для отправки/получения Yjs updates.
   *
   * @param dataChannel — WebRTC DataChannel для передачи updates
   */
  connect(dataChannel: RTCDataChannel): void {
    if (!dataChannel) {
      console.error("[YjsManager] Cannot connect — DataChannel is null");
      return;
    }

    this.dataChannel = dataChannel;

    // При открытии DataChannel отправляем sync-request и свой полный state
    dataChannel.addEventListener("open", () => {
      console.log(`[YjsManager] DataChannel opened for peer: ${this.localPeerId}`);

      // Отправляем sync-request для запроса полного state от удалённого пира
      this.sendRoomMessage({
        __yjs__: false,
        type: "sync-request",
        peerId: this.localPeerId,
      });

      // Отправляем peer-joined
      this.sendRoomMessage({
        __yjs__: false,
        type: "peer-joined",
        peerId: this.localPeerId,
      });
    });

    // При получении сообщения
    dataChannel.addEventListener("message", (event: MessageEvent) => {
      try {
        const message = JSON.parse(event.data as string) as YjsUpdateMessage | YjsRoomMessage;
        this.handleIncomingMessage(message);
      } catch (_err) {
        const err = _err;
        console.error("[YjsManager] Failed to parse incoming message:", err);
      }
    });

    dataChannel.addEventListener("close", () => {
      console.log(`[YjsManager] DataChannel closed for peer: ${this.localPeerId}`);
      this.dataChannel = null;
    });

    dataChannel.addEventListener("error", (event: Event) => {
      console.error("[YjsManager] DataChannel error:", event);
    });

    console.log(`[YjsManager] Connected to DataChannel for peer: ${this.localPeerId}`);
  }

  /**
   * Обработка входящего сообщения от удалённого пира.
   *
   * Определяет тип сообщения (Yjs update или room event) и обрабатывает соответственно.
   */
  private handleIncomingMessage(message: YjsUpdateMessage | YjsRoomMessage): void {
    const isYjsUpdate = (message as YjsUpdateMessage).__yjs__ === true;

    if (isYjsUpdate) {
      const yjsMsg = message as YjsUpdateMessage;
      try {
        // Конвертируем base64 обратно в Uint8Array
        const binaryString = atob(yjsMsg.update);
        const bytes = new Uint8Array(binaryString.length);
        for (let i = 0; i < binaryString.length; i++) {
          bytes[i] = binaryString.charCodeAt(i);
        }

        // Применяем обновление к Yjs Doc с указанием origin (source peer)
        // Origin используется для предотвращения петель: Yjs не будет триггерить
        // local update callback для updates от других пиров
        Y.applyUpdate(this.doc, bytes, yjsMsg.peerId);

        console.log(`[YjsManager] Applied Yjs update from peer: ${yjsMsg.peerId} (${bytes.length} bytes)`);

        // Уведомляем внешних слушателей update
        for (const listener of this.updateListeners) {
          try {
            listener(message as YjsUpdateMessage);
          } catch (err) {
            console.error("[YjsManager] Error in update listener:", err);
          }
        }
      } catch (err) {
        console.error("[YjsManager] Failed to apply Yjs update:", err);
      }
    } else {
      const roomMsg = message as YjsRoomMessage;
      this.handleRoomMessage(roomMsg);
    }
  }

  /**
   * Обработка room сообщений (peer join/leave, sync).
   */
  private handleRoomMessage(msg: YjsRoomMessage): void {
    switch (msg.type) {
      case "sync-request": {
        // Удалённый пир запрашивает наш полный state
        // Отправляем ему текущее состояние doc
        const update = Y.encodeStateAsUpdate(this.doc);
        const binaryString = btoa(String.fromCharCode(...update));
        this.sendRoomMessage({
          __yjs__: false,
          type: "sync-response",
          peerId: this.localPeerId,
          update: binaryString,
        });
        break;
      }

      case "sync-response": {
        // Применяем полный state от удалённого пира
        if (msg.update) {
          try {
            const binaryString = atob(msg.update);
            const bytes = new Uint8Array(binaryString.length);
            for (let i = 0; i < binaryString.length; i++) {
              bytes[i] = binaryString.charCodeAt(i);
            }
            // Merge state: Y.mergeUpdates объединяет состояния CRDT
            Y.applyUpdate(this.doc, bytes, msg.peerId);
            console.log(`[YjsManager] Applied full state sync from peer: ${msg.peerId}`);
          } catch (err) {
            console.error("[YjsManager] Failed to apply sync response:", err);
          }
        }
        break;
      }

      case "peer-joined":
        for (const listener of this.roomListeners) {
          try {
            listener("peer-joined", msg.peerId);
          } catch (err) {
            console.error("[YjsManager] Error in room listener:", err);
          }
        }
        break;

      case "peer-left":
        for (const listener of this.roomListeners) {
          try {
            listener("peer-left", msg.peerId);
          } catch (err) {
            console.error("[YjsManager] Error in room listener:", err);
          }
        }
        break;
    }
  }

  /**
   * Обработка Yjs update events.
   *
   * Когда локальное изменение изменяет Yjs Doc, Yjs генерирует binary update.
   * Мы сериализуем его в base64 и отправляем через DataChannel всем пирам.
   *
   * Параметр `origin` в callback:
   * - null: обновление создано локально (нужно отправить по сети)
   * string: обновление создано пиром с указанным peerId (нужно применить локально)
   */
  private handleYjsUpdate(update: Uint8Array, _origin: unknown): void {
    // Сериализуем binary update в base64
    const base64 = btoa(String.fromCharCode(...update));

    const message: YjsUpdateMessage = {
      __yjs__: true,
      update: base64,
      peerId: this.localPeerId,
    };

    // Отправляем через DataChannel
    this.sendYjsUpdate(message);
  }

  /**
   * Отправка Yjs update через DataChannel.
   */
  private sendYjsUpdate(message: YjsUpdateMessage): void {
    if (!this.dataChannel || this.dataChannel.readyState !== "open") {
      console.warn("[YjsManager] Cannot send update — DataChannel not open");
      return;
    }

    try {
      this.dataChannel.send(JSON.stringify(message));
      console.log(`[YjsManager] Sent update to peer: ${this.localPeerId} (${message.update.length} chars)`);
    } catch (err) {
      console.error("[YjsManager] Failed to send update:", err);
    }
  }

  /**
   * Отправка room сообщения через DataChannel.
   */
  private sendRoomMessage(message: YjsRoomMessage): void {
    if (!this.dataChannel || this.dataChannel.readyState !== "open") {
      console.warn("[YjsManager] Cannot send room message — DataChannel not open");
      return;
    }

    try {
      this.dataChannel.send(JSON.stringify(message));
      console.log(`[YjsManager] Sent room message: ${message.type}`);
    } catch (err) {
      console.error("[YjsManager] Failed to send room message:", err);
    }
  }

  /**
   * Обработка глубоких изменений в objectsMap.
   *
   * Yjs observeDeep триггерится для изменений вложенных структур (Y.Map values).
   * Мы парсим path и delta для определения типа изменения.
   */
  private handleObjectsDeepChange(events: Array<Y.YEvent<Y.Map<unknown>>>): void {
    for (const event of events) {
      try {
        // Определяем objectId из path
        const objectId = event.path[0];
        if (!objectId) continue;

        // Всегда сообщаем "update" — для простого UI это достаточно
        const eventType: ChangeEventType = "update";

        // Уведомляем слушателей
        for (const listener of this.objectsChangeListeners) {
          try {
            listener(eventType, { objectId });
          } catch (err) {
            console.error("[YjsManager] Error in objects change listener:", err);
          }
        }
      } catch (err) {
        console.error("[YjsManager] Error in handleObjectsDeepChange:", err);
      }
    }
  }

  /**
   * Обработка изменений в notesText.
   */
  private handleNotesChange(_event: Y.YTextEvent): void {
    try {
      for (const listener of this.notesChangeListeners) {
        try {
          listener("update", { timestamp: Date.now() });
        } catch (err) {
          console.error("[YjsManager] Error in notes change listener:", err);
        }
      }
    } catch (err) {
      console.error("[YjsManager] Error in handleNotesChange:", err);
    }
  }

  // ==================== Public API ====================

  /**
   * Получить Y.Map объектов.
   * @returns Y.Map где ключ = objectId, значение = Y.Map с данными объекта
   */
  getObjects(): Y.Map<Y.Map<unknown>> {
    return this.objectsMap;
  }

  /**
   * Получить Y.Text заметок.
   * @returns Y.Text с синхронизированным текстом заметок
   */
  getNotes(): Y.Text {
    return this.notesText;
  }

  /**
   * Получить текстовое содержимое заметок.
   */
  getNotesText(): string {
    return this.notesText.toString();
  }

  /**
   * Установить текстовое содержимое заметок.
   * Это создаст CRDT обновление которое будет синхронизировано.
   */
  setNotesText(text: string): void {
    const current = this.notesText.toString();
    if (current === text) return;
    this.notesText.delete(0, current.length);
    this.notesText.insert(0, text);
  }

  /**
   * Добавить новый table object в objectsMap.
   *
   * Yjs автоматически создаст уникальный ключ для объекта и синхронизирует
   * обновление всем подключённым пирам через DataChannel.
   *
   * @param data — данные объекта (позиция, тип и т.д.)
   * @returns ID созданного объекта
   */
  addObject(data: DefaultTableObjectData): string {
    const objectId = crypto.randomUUID();

    // Создаём вложенный Y.Map для данных объекта
    const objectData = new Y.Map<unknown>();
    objectData.set("x", data.x);
    objectData.set("y", data.y);
    objectData.set("rotation", data.rotation);
    objectData.set("scale", data.scale);
    objectData.set("type", data.type);
    if (data.fileId) objectData.set("fileId", data.fileId);
    if (data.name) objectData.set("name", data.name);
    objectData.set("id", objectId);

    // Устанавливаем в objectsMap — это триггернет Yjs update
    this.objectsMap.set(objectId, objectData);

    console.log(`[YjsManager] Added object: ${objectId}`);
    return objectId;
  }

  /**
   * Обновить существующий table object.
   *
   * @param objectId — ID объекта для обновления
   * @param updates — частичные данные для обновления (merge с существующими)
   */
  updateObject(objectId: string, updates: Partial<Omit<TableObjectData, "id">>): void {
    const existing = this.objectsMap.get(objectId);
    if (!existing) {
      console.warn(`[YjsManager] Object not found for update: ${objectId}`);
      return;
    }

    for (const [key, value] of Object.entries(updates)) {
      existing.set(key, value);
    }
    console.log(`[YjsManager] Updated object: ${objectId}`);
  }

  /**
   * Удалить table object из objectsMap.
   *
   * @param objectId — ID объекта для удаления
   */
  removeObject(objectId: string): void {
    this.objectsMap.delete(objectId);
    console.log(`[YjsManager] Removed object: ${objectId}`);
  }

  /**
   * Получить данные всех объектов.
   *
   * @returns Map<objectId, TableObjectData>
   */
  getAllObjects(): Map<string, TableObjectData> {
    const result = new Map<string, TableObjectData>();

    this.objectsMap.forEach((valueYMap: Y.Map<unknown>, key: string) => {
      try {
        const data: Partial<TableObjectData> = {};
        valueYMap.forEach((v: unknown, k: string) => {
          if (typeof v === "number" || typeof v === "string") {
            (data as Record<string, unknown>)[k] = v;
          }
        });
        result.set(key, data as TableObjectData);
      } catch (err) {
        console.error(`[YjsManager] Failed to read object ${key}:`, err);
      }
    });

    return result;
  }

  /**
   * Получить количество объектов.
   */
  getObjectCount(): number {
    return this.objectsMap.size;
  }

  /**
   * Подписаться на входящие Yjs updates.
   *
   * @param callback — вызывается при каждом полученном update от другого пира
   * @returns функция для удаления слушателя
   */
  onUpdate(callback: YjsCallback): () => void {
    this.updateListeners.add(callback);
    return () => {
      this.updateListeners.delete(callback);
    };
  }

  /**
   * Подписаться на room events (peer join/leave).
   *
   * @param callback — вызывается при подключении/отключении пира
   * @returns функция для удаления слушателя
   */
  onRoomEvent(callback: RoomCallback): () => void {
    this.roomListeners.add(callback);
    return () => {
      this.roomListeners.delete(callback);
    };
  }

  /**
   * Подписаться на изменения в objectsMap.
   *
   * @param callback — вызывается при каждом изменении объектов
   * @returns функция для удаления слушателя
   */
  onObjectsChange(callback: ObjectsChangeCallback): () => void {
    this.objectsChangeListeners.add(callback);
    return () => {
      this.objectsChangeListeners.delete(callback);
    };
  }

  /**
   * Подписаться на изменения в notesText.
   *
   * @param callback — вызывается при каждом изменении текста заметок
   * @returns функция для удаления слушателя
   */
  onNotesChange(callback: ObjectsChangeCallback): () => void {
    this.notesChangeListeners.add(callback);
    return () => {
      this.notesChangeListeners.delete(callback);
    };
  }

  /**
   * Получить Yjs Doc для прямой работы (advanced use case).
   */
  getDoc(): Y.Doc {
    return this.doc;
  }

  /**
   * Получить peer ID.
   */
  getPeerId(): string {
    return this.localPeerId;
  }

  /**
   * Проверить инициализацию.
   */
  isInitialized(): boolean {
    return this.initialized;
  }

  /**
   * Очистка ресурсов.
   */
  close(): void {
    // Отправляем peer-left
    this.sendRoomMessage({
      __yjs__: false,
      type: "peer-left",
      peerId: this.localPeerId,
    });

    // Убираем все слушатели Yjs
    // Yjs observeDeep/unobserve не нужны — observeDeep сам очищается при doc.destroy()
    this.doc.off("update", this.handleYjsUpdate.bind(this));

    // Очищаем коллекции колбэков
    this.updateListeners.clear();
    this.roomListeners.clear();
    this.objectsChangeListeners.clear();
    this.notesChangeListeners.clear();

    this.dataChannel = null;
    this.initialized = false;

    console.log(`[YjsManager] Closed for peer: ${this.localPeerId}`);
  }
}